### ISSUE TITLE
[Bug] Driftwood Giant kill broken

### ISSUE THREAD

**Issue by JohnMetroid** [Wexop/RandomEnemiesSize#2]
Hey there,

encountered a somewhat-tiny Driftwood Giant that picked someone up but couldn't kill them.  Similar action to the regular giant, so that kill may also be broken when resized.

**Comment by Wexop** [comment]
Hey ! Thanks for the report,

Do every small enemies had this issue, or only Driftwood Giant ? 

My mod don't change monster interaction with the player, so if others monsters work maybe it's just the monster mod that have an issue or my mod have an incompatibility with it.

Can you try to spawn this mob with a bigger size and see if he can kill you or your friends ?

**Comment by JohnMetroid** [comment]
we tried to recreate it for a little while recently and couldn't get anything to noticeably break.  Not sure there's anything to be done at the moment.

The mod is really fun by the way.  Have you considered an option to use something like a normal distribution to make the extremely small/large monsters feel a bit more rare?

**Comment by Wexop** [comment]
Hey !
Ok, maybe one update fixed it 🤔

If you have any issue or suggestions feel free to create an issue 🙂

I will close this one because it's been 26 days without news on it so i guess this is fixed.

Also there is a config to set the chance for any enemies to have a random size, if that is what you were talking about !

Have fun with the mod 👍🏻
