### ISSUE TITLE
[Idea] Turn off random sizes for modded enemies

### ISSUE THREAD

**Issue by CR1MXN** [Wexop/RandomEnemiesSize#4]
Could you make an option in the config that doesn't force the Randomenemysize mod to effect modded enemies? Or some way for us to know the original size of an enemy specifically modded ones that are not listed on the generator you generously made for people to use.

**Comment by Wexop** [comment]
Hey !

Yes i can totaly do a config to enable or not size effect on modded monster, that's a good idea 👍

I don't think you need to know the original scale of a monster, because my mod simply multiply the original scale (so you don't need to calculate anything !)

So any monster with size of 0.5 will be half his size, and any monster with size of 2 will 2 times bigger :)

Hope this response help you, feel free to send a message for any question !

**Comment by Wexop** [comment]
This feature is in the v1.1.4 :)
