### ISSUE TITLE
question

### ISSUE THREAD

**Issue by Mickael46999** [Wexop/RandomEnemiesSize#7]
it work with vanilla clients? If im the host and have the mod, other people without it can see the changes??

**Comment by Wexop** [comment]
Hello ! 
Every player must have RandomEnemiesSize to work.
But i made a host only version of this mod, you can find it [here ](https://thunderstore.io/c/lethal-company/p/Wexop/RandomEnemiesSizeHostOnly/)

This host only version work well for monster, but I recommend you to disable hazards in configs because there are some issues

Have fun !
